# Generated by Django 4.1.7 on 2023-03-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fablabmedia",
            name="advanced_mobile",
            field=models.FileField(blank=True, upload_to="media", verbose_name="file"),
        ),
    ]
