# Generated by Django 3.2.10 on 2022-02-06 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_initial'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qufablab', '0002_auto_20220206_1546'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticlePage',
            new_name='QuArticlePage',
        ),
    ]
