# Generated by Django 3.2.12 on 2022-04-18 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_area'),
        ('qufablab', '0002_alter_flexpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisation.person'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisation.organisation'),
        ),
    ]
