# Generated by Django 3.2.10 on 2022-02-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('qufablab', '0003_rename_articlepage_quarticlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarticlepage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page'),
        ),
    ]
