# Generated by Django 3.2.10 on 2022-02-06 15:03

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtailcache.cache


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('core', '0002_initial'),
        ('snippets', '0001_initial'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('qufablab', '0004_alter_quarticlepage_page_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='wagtailcore.page')),
                ('index', models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255)),
                ('og_image_alt', models.CharField(blank=True, max_length=255, null=True)),
                ('og_type', models.CharField(choices=[('website', 'website'), ('article', 'article'), ('profile', 'profile')], default='website', max_length=255)),
                ('tw_size', models.CharField(choices=[('summary_large_image', 'summary_large_image'), ('summary', 'summary'), ('player', 'player')], default='summary_large_image', max_length=255)),
                ('date', models.DateField()),
                ('introduction', models.CharField(max_length=150)),
                ('body', wagtail.core.fields.RichTextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.author')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fablabimage')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fablabimage')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='snippets.tag')),
            ],
            options={
                'verbose_name': 'Artikel',
                'abstract': False,
            },
            bases=(wagtailcache.cache.WagtailCacheMixin, 'wagtailcore.page'),
        ),
        migrations.DeleteModel(
            name='QuArticlePage',
        ),
    ]
