# Generated by Django 3.2.12 on 2022-04-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qufablab', '0009_auto_20220404_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepage',
            name='author',
        ),
    ]
