# Generated by Django 3.2.14 on 2022-07-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customformsubmission",
            name="date",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
