# Generated by Django 3.2.14 on 2022-07-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomFormSubmission',
        ),
    ]
