# Generated by Django 3.2.13 on 2022-05-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='intro',
        ),
    ]
