# Generated by Django 3.2.12 on 2022-04-10 18:28

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20220410_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=254, verbose_name='Last Name')),
                ('employment', models.CharField(max_length=254)),
                ('link', models.URLField(blank=True, max_length=254, null=True)),
                ('since', models.DateField()),
                ('career', models.CharField(blank=True, max_length=254, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=254, null=True)),
                ('expert', models.CharField(blank=True, max_length=254, null=True)),
                ('projects', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fablabimage')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_member', to='models.project')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test', to='models.person')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
