# Generated by Django 3.2.16 on 2023-02-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("projects", "0002_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.fablabimage",
            ),
        ),
    ]
