repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        args: ["--target-version", "py38"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        types_or: [javascript, json, yaml]
  - repo: https://github.com/rtts/djhtml
    rev: "3.0.1"
    hooks:
      - id: djhtml
