# Generated by Django 3.2.15 on 2022-09-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="model",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="title",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
