# Generated by Django 3.2.15 on 2022-09-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_auto_20220921_1807"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="area",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
