# Generated by Django 3.2.15 on 2022-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_device_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
