# Generated by Django 3.2.15 on 2022-09-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_fablabimage_file_hash"),
        ("devices", "0004_device_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.fablabimage",
            ),
        ),
    ]
