# Generated by Django 3.2.12 on 2022-04-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
