# Generated by Django 3.2.12 on 2022-04-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220410_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='core.person'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
