# Generated by Django 3.2.12 on 2022-04-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220410_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
