# Generated by Django 3.2.12 on 2022-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="titel",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="First Name"
            ),
        ),
    ]
