# Generated by Django 3.2.12 on 2022-04-15 18:04

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.contrib.modeladmin.options


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.contrib.modeladmin.options.ModelAdmin, models.Model),
        ),
        migrations.CreateModel(
            name='PersonAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
            bases=(wagtail.contrib.modeladmin.options.ModelAdmin, models.Model),
        ),
    ]
