# Generated by Django 3.2.12 on 2022-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='link',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
