# Generated by Django 3.2.12 on 2022-04-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisation.organisation'),
        ),
    ]
