# Generated by Django 3.2.12 on 2022-04-11 17:42

import abstract.blocks.member
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_person_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=wagtail.core.fields.StreamField([('member', abstract.blocks.member.PersonChooserBlock())], blank=True),
        ),
    ]
