# Generated by Django 3.2.12 on 2022-04-11 17:44

import abstract.blocks.member
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_project_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=wagtail.core.fields.StreamField([('member', wagtail.core.blocks.ListBlock(abstract.blocks.member.PersonChooserBlock))], blank=True),
        ),
    ]
