# Generated by Django 3.2.12 on 2022-04-21 14:59

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_auto_20220421_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='link',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_role', to='organisation.project'),
        ),
    ]
