# Generated by Django 3.2.12 on 2022-04-21 15:12

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0005_alter_role_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="link",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_roles",
                to="organisation.project",
            ),
        ),
    ]
