# Generated by Django 3.2.12 on 2022-04-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_alter_role_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='career',
        ),
        migrations.RemoveField(
            model_name='person',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='person',
            name='en_career',
        ),
        migrations.RemoveField(
            model_name='person',
            name='en_employment',
        ),
        migrations.RemoveField(
            model_name='person',
            name='en_expert',
        ),
        migrations.RemoveField(
            model_name='person',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='person',
            name='since',
        ),
    ]
