# Generated by Django 3.2.12 on 2022-04-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_remove_project_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='organisation.person'),
        ),
    ]
