# Generated by Django 3.2.12 on 2022-04-11 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_alter_member_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='person',
        ),
    ]
