# Generated by Django 3.2.12 on 2022-04-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0007_auto_20220421_2320"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="description",
        ),
        migrations.RemoveField(
            model_name="person",
            name="en_description",
        ),
    ]
