# Generated by Django 3.2.13 on 2022-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0010_auto_20220427_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Beschreibung'),
        ),
    ]
