# Generated by Django 3.2.13 on 2022-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='adress',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Titel'),
        ),
    ]
