# Generated by Django 3.2.13 on 2022-05-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0011_auto_20220520_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(choices=[('0', 'none'), ('1', 'weekly')], default='none', max_length=255),
        ),
    ]
