# Generated by Django 3.2.13 on 2022-05-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_auto_20220428_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
