# Generated by Django 3.2.13 on 2022-05-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0013_alter_event_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("0", "none"),
                    ("1", "Lehre"),
                    ("2", "Offenes Angebot"),
                    ("3", "Schülerkurse"),
                    ("4", "Workshop"),
                    ("5", "Extern"),
                ],
                default="none",
                max_length=255,
            ),
        ),
    ]
