# Generated by Django 3.2.14 on 2022-08-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_auto_20220704_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('0', 'none'), ('1', 'Lehre'), ('2', 'Offenes Angebot'), ('3', 'Schülerkurse'), ('4', 'Workshop'), ('5', 'Extern'), ('6', 'FabLab Event')], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Titel'),
        ),
    ]
