# Generated by Django 3.2.15 on 2022-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0017_auto_20220810_1356"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("none", "none"),
                    ("teach", "Lehre"),
                    ("open", "Offenes Angebot"),
                    ("student", "Schülerkurse"),
                    ("workshop", "Workshop"),
                    ("external", "Extern"),
                    ("6", "FabLab Event"),
                ],
                default="none",
                max_length=255,
            ),
        ),
    ]
