# Generated by Django 3.2.16 on 2023-01-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0020_role_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(
                blank=True, max_length=280, null=True, verbose_name="Beschreibung"
            ),
        ),
    ]
