# Generated by Django 3.2.14 on 2022-08-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="variation_color",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
