# Generated by Django 3.2.16 on 2022-12-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("global", "0002_globalsettings_variation_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="surface_color_one",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="surface_color_two",
        ),
        migrations.RemoveField(
            model_name="globalsettings",
            name="text_color",
        ),
    ]
