from .article import *  # noqa
from .articleIndex import *  # noqa
from .deviceIndex import *  # noqa
from .flex import *  # noqa
from .folder import *  # noqa
from .forms import *  # noqa
from .home import *  # noqa
from .links import *  # noqa
from .project import *  # noqa
from .projectIndex import *  # noqa
