# Generated by Django 3.2.13 on 2022-06-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birdsong', '0006_auto_20220428_0558'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='birdsong.contact')),
            ],
            options={
                'abstract': False,
            },
            bases=('birdsong.contact',),
        ),
    ]
