# Generated by Django 3.2.10 on 2022-01-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qu_fablab', '0013_auto_20220131_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='quindexcategorypage',
            name='introduction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quindexpage',
            name='introduction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quarticlepage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='quflexpage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='qufolderpage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='quhomepage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='quindexcategorypage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='quindexpage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='quprojectpage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
    ]
