# Generated by Django 3.2.10 on 2022-02-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qu_fablab', '0017_linkcollections_qucollectionpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkcollections',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='linkcollections',
            name='link_title',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkcollections',
            name='link_url',
            field=models.URLField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
