# Generated by Django 3.2.10 on 2022-02-02 10:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qu_fablab', '0018_auto_20220201_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qucollectionpage',
            options={'verbose_name': 'Collection Seite'},
        ),
        migrations.AddField(
            model_name='qucollectionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock()), ('expire', wagtail.core.blocks.DateBlock())])))], default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LinkCollections',
        ),
    ]
