# Generated by Django 3.2.10 on 2022-02-02 10:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qu_fablab', '0019_auto_20220202_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qucollectionpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='qucollectionpage',
            name='body',
        ),
        migrations.CreateModel(
            name='LinkCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_url', models.URLField(max_length=255)),
                ('link_title', models.CharField(max_length=255)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='qu_fablab.qucollectionpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
