# Generated by Django 3.2.10 on 2022-02-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qu_fablab', '0020_auto_20220202_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkcollections',
            old_name='expire_date',
            new_name='expire',
        ),
        migrations.RenameField(
            model_name='linkcollections',
            old_name='link_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='linkcollections',
            old_name='link_url',
            new_name='url',
        ),
    ]
