# Generated by Django 3.2.10 on 2022-02-02 12:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('qu_fablab', '0021_auto_20220202_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_link', to='qu_fablab.qucollectionpage')),
            ],
        ),
        migrations.AlterModelOptions(
            name='linkcollections',
            options={'ordering': ['expire']},
        ),
        migrations.CreateModel(
            name='GrabberCollections',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='qu_fablab.page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('parentTest', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='qu_fablab.qucollectionpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('qu_fablab.page', models.Model),
        ),
    ]
