# Generated by Django 3.2.10 on 2022-02-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('qu_fablab', '0025_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='qucollectionpage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='qucollectionpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='QuCollectionPage',
        ),
    ]
