# Generated by Django 3.2.10 on 2022-02-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qu_fablab', '0028_auto_20220204_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectauthor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='projectauthor',
            name='last_name',
        ),
    ]
