# Generated by Django 3.2.10 on 2022-02-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qu_fablab', '0030_alter_quprojectpage_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectAuthor',
        ),
    ]
