# Generated by Django 3.2.10 on 2022-02-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('qu_fablab', '0031_delete_projectauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quprojectpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quprojectpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quprojectpage',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='quprojectpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ProjectPageLink',
        ),
        migrations.DeleteModel(
            name='QuProjectPage',
        ),
    ]
