# Generated by Django 3.2.10 on 2022-02-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('qu_fablab', '0032_auto_20220205_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuIndexCategoryPage',
        ),
    ]
