# Generated by Django 3.2.10 on 2022-02-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qu_fablab', '0034_qusearchpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qusearchpage',
            options={'verbose_name': 'Such Seite'},
        ),
    ]
