# Generated by Django 4.1.7 on 2023-02-17 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_flexpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleindexpage",
            options={"verbose_name": "Artikel Index Seite"},
        ),
    ]
