# Generated by Django 4.1.7 on 2023-04-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("model", models.CharField(blank=True, max_length=250, null=True)),
                ("area", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("amount", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.fablabimage",
                    ),
                ),
            ],
        ),
    ]
