# Generated by Django 4.1.7 on 2023-04-17 18:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=254, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=254, verbose_name="Last Name"),
                ),
                ("link", models.URLField(blank=True, max_length=254, null=True)),
                (
                    "responsibility",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.fablabimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
