# Generated by Django 4.1.10 on 2023-08-03 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="title",
            new_name="personal_title",
        ),
    ]
