# Generated by Django 4.1.10 on 2023-08-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0002_rename_title_person_personal_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="personal_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Title"
            ),
        ),
    ]
