# Generated by Django 3.2.12 on 2022-04-10 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.DeleteModel(
            name='DeviceCategory',
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
