# Generated by Django 3.2.10 on 2022-02-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategory',
            options={'verbose_name': 'Gerätekategorie', 'verbose_name_plural': 'Gerätekategorien'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'verbose_name': 'Projektkategorie', 'verbose_name_plural': 'Projektkategorien'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterUniqueTogether(
            name='devicecategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='projectcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='devicecategory',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='devicecategory',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='translation_key',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='translation_key',
        ),
    ]
