# Generated by Django 3.2.12 on 2022-04-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
