# Generated by Django 3.2.12 on 2022-04-10 12:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('snippets', '0004_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='First name')),
                ('employment', models.CharField(max_length=254)),
                ('link', models.URLField(max_length=254)),
                ('since', models.DateField()),
                ('career', models.CharField(max_length=254)),
                ('responsibility', models.CharField(max_length=254)),
                ('expert', models.CharField(max_length=254)),
                ('projects', models.CharField(max_length=254)),
                ('description', models.TextField(max_length=254)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fablabimage')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
