# Generated by Django 3.2.10 on 2022-02-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220206_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpagepage',
            name='title',
        ),
    ]
