# Generated by Django 3.2.12 on 2022-04-14 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
        ('base', '0003_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicepage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisation.devicecategory'),
        ),
    ]
