# Generated by Django 3.2.10 on 2022-02-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('base', '0003_remove_collectionpagepage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpagepage',
            name='grabber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='collectionpagepage',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
