# Generated by Django 3.2.12 on 2022-04-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220414_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceindexpage',
            options={'verbose_name': 'Geräte'},
        ),
        migrations.AlterModelOptions(
            name='projectindexpage',
            options={'verbose_name': 'Projekte'},
        ),
    ]
