# Generated by Django 3.2.12 on 2022-04-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_personadmin_projectadmin'),
        ('base', '0007_auto_20220414_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organisation.projectcategory'),
        ),
    ]
