# Generated by Django 3.2.13 on 2022-04-24 09:53

import abstract.blocks.chooser
import abstract.blocks.spacer
from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailmedia.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_auto_20220423_1242"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [("title", wagtail.blocks.CharBlock(required=False))],
                            label="Überschrift",
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "h3",
                                            "ul",
                                            "link",
                                            "document-link",
                                            "image",
                                            "embed",
                                        ]
                                    ),
                                ),
                            ],
                            label="Absatz",
                        ),
                    ),
                    (
                        "split",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.TextBlock(required=False),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "ul",
                                            "document-link",
                                            "link",
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "accent",
                                    wagtail.blocks.BooleanBlock(required=False),
                                ),
                            ],
                            label="Split",
                        ),
                    ),
                    (
                        "grid",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("extrem", "1 x N"),
                                            ("large", "2 x N"),
                                            ("medium", "3 x N"),
                                            ("small", "4 x N"),
                                        ],
                                        help_text="Die Anzahl an Elementen in einer Horizontalen Reihe",
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "card",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.TextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ],
                                                    label="Karte",
                                                ),
                                            ),
                                            (
                                                "person",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "person",
                                                            abstract.blocks.chooser.PersonChooserBlock(
                                                                required=False
                                                            ),
                                                        )
                                                    ],
                                                    label="Person",
                                                ),
                                            ),
                                        ],
                                        label="Grid Elemente",
                                    ),
                                ),
                            ],
                            label="Grid",
                        ),
                    ),
                    (
                        "gallery",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "contain",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Wenn z.B. von Logos das Seitenverhältnis beibehalten bleiben soll, sodass das Logo nicht abgeschnitten wird.",
                                        label="Cointain Aspect Ratio",
                                        required=False,
                                    ),
                                ),
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("extrem", "1 x N"),
                                            ("large", "2 x N"),
                                            ("medium", "3 x N"),
                                            ("small", "4 x N"),
                                            ("tiny", "5 x N"),
                                        ],
                                        help_text="Die Anzahl an Elementen in einer Horizontalen Reihe",
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(),
                                            ),
                                            (
                                                "video",
                                                wagtailmedia.blocks.VideoChooserBlock(),
                                            ),
                                            (
                                                "embed",
                                                wagtail.embeds.blocks.EmbedBlock(),
                                            ),
                                        ]
                                    ),
                                ),
                            ],
                            label="Galerie",
                        ),
                    ),
                    ("spacer", abstract.blocks.spacer.SpacerBlock(label="Spacer")),
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "video",
                                    wagtailmedia.blocks.VideoChooserBlock(
                                        icon="media", required=False
                                    ),
                                ),
                            ],
                            label="Video",
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                            ],
                            label="Bild",
                        ),
                    ),
                    (
                        "embed",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(required=False),
                                ),
                            ],
                            label="Website einbetten",
                        ),
                    ),
                    (
                        "html",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "code",
                                    wagtail.blocks.RawHTMLBlock(required=False),
                                )
                            ],
                            label="HTML",
                        ),
                    ),
                    (
                        "table",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "table",
                                    wagtail.contrib.table_block.blocks.TableBlock(
                                        required=False
                                    ),
                                )
                            ],
                            label="Tabelle",
                        ),
                    ),
                ],
                blank=True,
            ),
        ),
    ]
