# Generated by Django 3.2.13 on 2022-05-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('base', '0011_formfield_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AddField(
            model_name='formpage',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fablabimage'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='og_image_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='og_type',
            field=models.CharField(choices=[('website', 'website'), ('article', 'article'), ('profile', 'profile')], default='website', max_length=255),
        ),
        migrations.AddField(
            model_name='formpage',
            name='tw_size',
            field=models.CharField(choices=[('summary_large_image', 'summary_large_image'), ('summary', 'summary'), ('player', 'player')], default='summary_large_image', max_length=255),
        ),
    ]
