# Generated by Django 3.2.13 on 2022-05-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20220508_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpage',
            options={'verbose_name': 'Form Seite'},
        ),
    ]
