# Generated by Django 3.2.14 on 2022-07-29 18:59

import abstract.blocks.chooser
from django.db import migrations, models
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmedia.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_alter_formfield_field_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formpage",
            name="body",
        ),
        migrations.AddField(
            model_name="formpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [("title", wagtail.blocks.CharBlock(required=False))],
                            label="Überschrift",
                        ),
                    ),
                    (
                        "paragraph",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "h3",
                                            "ul",
                                            "link",
                                            "document-link",
                                            "image",
                                            "embed",
                                        ]
                                    ),
                                ),
                            ],
                            label="Absatz",
                        ),
                    ),
                    (
                        "split",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.TextBlock(required=False)),
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=[
                                            "bold",
                                            "italic",
                                            "ul",
                                            "document-link",
                                            "link",
                                        ],
                                        required=False,
                                    ),
                                ),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                ("accent", wagtail.blocks.BooleanBlock(required=False)),
                            ],
                            label="Split",
                        ),
                    ),
                    (
                        "grid",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("extrem", "1 x N"),
                                            ("large", "2 x N"),
                                            ("medium", "3 x N"),
                                            ("small", "4 x N"),
                                        ],
                                        help_text="Die Anzahl an Elementen in einer Horizontalen Reihe",
                                    ),
                                ),
                                ("accent", wagtail.blocks.BooleanBlock(required=False)),
                                (
                                    "cards",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "card",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "title",
                                                            wagtail.blocks.CharBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "image",
                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "text",
                                                            wagtail.blocks.TextBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                        (
                                                            "page",
                                                            wagtail.blocks.PageChooserBlock(
                                                                required=False
                                                            ),
                                                        ),
                                                    ],
                                                    label="Karte",
                                                ),
                                            ),
                                            (
                                                "person",
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        (
                                                            "person",
                                                            abstract.blocks.chooser.PersonChooserBlock(
                                                                required=False
                                                            ),
                                                        )
                                                    ],
                                                    label="Person",
                                                ),
                                            ),
                                        ],
                                        label="Grid Elemente",
                                    ),
                                ),
                            ],
                            label="Grid",
                        ),
                    ),
                    (
                        "gallery",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "contain",
                                    wagtail.blocks.BooleanBlock(
                                        help_text="Wenn z.B. von Logos das Seitenverhältnis beibehalten bleiben soll, sodass das Logo nicht abgeschnitten wird.",
                                        label="Cointain Aspect Ratio",
                                        required=False,
                                    ),
                                ),
                                (
                                    "layout",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("extrem", "1 x N"),
                                            ("large", "2 x N"),
                                            ("medium", "3 x N"),
                                            ("small", "4 x N"),
                                            ("tiny", "5 x N"),
                                        ],
                                        help_text="Die Anzahl an Elementen in einer Horizontalen Reihe",
                                    ),
                                ),
                                ("accent", wagtail.blocks.BooleanBlock(required=False)),
                                (
                                    "cards",
                                    wagtail.blocks.StreamBlock(
                                        [
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(),
                                            ),
                                            (
                                                "video",
                                                wagtailmedia.blocks.VideoChooserBlock(),
                                            ),
                                            (
                                                "embed",
                                                wagtail.embeds.blocks.EmbedBlock(),
                                            ),
                                        ]
                                    ),
                                ),
                            ],
                            label="Galerie",
                        ),
                    ),
                    (
                        "banner",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.TextBlock(required=False)),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                (
                                    "illustration",
                                    wagtail.blocks.BooleanBlock(required=False),
                                ),
                            ],
                            label="Banner",
                        ),
                    ),
                    (
                        "video",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "video",
                                    wagtailmedia.blocks.VideoChooserBlock(
                                        icon="media", required=False
                                    ),
                                ),
                                ("accent", wagtail.blocks.BooleanBlock(required=False)),
                            ],
                            label="Video",
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=False
                                    ),
                                ),
                                ("accent", wagtail.blocks.BooleanBlock(required=False)),
                            ],
                            label="Bild",
                        ),
                    ),
                    (
                        "embed",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "embed",
                                    wagtail.embeds.blocks.EmbedBlock(required=False),
                                ),
                                ("accent", wagtail.blocks.BooleanBlock(required=False)),
                            ],
                            label="Website einbetten",
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("singleline", "Single line text"),
                    ("multiline", "Multi-line text"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("url", "URL"),
                    ("checkbox", "Checkbox"),
                    ("checkboxes", "Checkboxes"),
                    ("dropdown", "Drop down"),
                    ("multiselect", "Multiple select"),
                    ("radio", "Radio buttons"),
                    ("date", "Date"),
                    ("datetime", "Date/time"),
                    ("hidden", "Hidden field"),
                ],
                max_length=16,
                verbose_name="field type",
            ),
        ),
    ]
