# Generated by Django 3.2.15 on 2022-09-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailforms", "0005_alter_formsubmission_form_data"),
        ("forms", "0002_alter_customformsubmission_date"),
        ("wagtailcore", "0069_log_entry_jsonfield"),
        ("wagtailredirects", "0008_add_verbose_name_plural"),
        ("base", "0025_auto_20220825_1146"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DevicePage",
        ),
    ]
