# Generated by Django 3.2.15 on 2022-09-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_auto_20220924_1916"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formpage",
            old_name="response_text",
            new_name="response_message",
        ),
        migrations.AddField(
            model_name="formpage",
            name="response_subject",
            field=models.TextField(blank=True, null=True),
        ),
    ]
