# Generated by Django 3.2.15 on 2022-09-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_delete_devicepage"),
        ("base", "0027_auto_20220924_1927"),
    ]

    operations = []
