# Generated by Django 3.2.10 on 2022-01-23 14:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('housenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('plz', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('thingiverse', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('logo_title', models.CharField(blank=True, max_length=30, null=True)),
                ('brand_color', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True)),
                ('text_color', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True)),
                ('surface_color_one', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True)),
                ('surface_color_two', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True)),
                ('surface_color_three', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('data_protection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('impressum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fablabimage')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Seiten Konfiguration',
            },
        ),
    ]
