# Generated by Django 3.2.10 on 2022-01-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='surface_color_three',
        ),
    ]
