# Generated by Django 3.2.10 on 2022-01-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='housenumber',
            field=models.CharField(max_length=20),
        ),
    ]
