# Generated by Django 3.2.10 on 2022-01-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_settings', '0003_alter_adress_housenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='donate_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
