# Generated by Django 3.2.10 on 2022-02-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('site_settings', '0004_sitesettings_intern_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.fablabimage'),
        ),
    ]
