# Generated by Django 3.2.10 on 2022-01-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_settings', '0004_adress_donate_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='donate_page',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='adress',
            name='data_protection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='adress',
            name='impressum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
