# Generated by Django 3.2.10 on 2022-01-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20220109_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='thingiverse',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='adress',
            name='youtube',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
