# Generated by Django 3.2.10 on 2022-02-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sponsor_logo_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo_alt_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
