# Generated by Django 3.2.10 on 2022-01-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('site_settings', '0006_auto_20220109_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Footer',
        ),
    ]
