# Generated by Django 4.1.7 on 2023-07-26 23:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_flexpage_body_alter_formpage_content_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchPage",
        ),
    ]
