# Generated by Django 3.2.12 on 2022-04-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Project Name')),
            ],
        ),
    ]
