# Generated by Django 4.1.7 on 2023-07-26 23:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("global", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalsettings",
            name="search",
        ),
    ]
