# Generated by Django 3.2.10 on 2022-01-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0011_auto_20220131_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexcategorypage',
            name='introduction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='introduction',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='devicepage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='flexpage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='folderpage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='indexcategorypage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='index',
            field=models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=255),
        ),
    ]
