# Generated by Django 3.2.10 on 2022-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0013_auto_20220131_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='introduction',
            field=models.CharField(max_length=150),
        ),
    ]
