# Generated by Django 3.2.10 on 2022-02-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0017_auto_20220204_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='body',
        ),
    ]
