# Generated by Django 3.2.10 on 2022-01-10 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fablab', '0023_auto_20220109_1155'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceIndexPage',
            new_name='IndexCategoryPage',
        ),
        migrations.RenameModel(
            old_name='ProjectIndexPage',
            new_name='IndexPage',
        ),
        migrations.DeleteModel(
            name='ArticleIndexPage',
        ),
    ]
