# Generated by Django 3.2.10 on 2022-01-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0024_auto_20220110_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': 'Artikel Seite'},
        ),
        migrations.AlterModelOptions(
            name='devicepage',
            options={'verbose_name': 'Geräte Seite'},
        ),
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Flexible Seite'},
        ),
        migrations.AlterModelOptions(
            name='folderpage',
            options={'verbose_name': 'Ordner'},
        ),
        migrations.AlterModelOptions(
            name='indexcategorypage',
            options={'verbose_name': 'Index Seite mit Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'Index Seite'},
        ),
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name': 'Projekt Seite'},
        ),
    ]
