# Generated by Django 3.2.10 on 2022-01-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fablab', '0025_auto_20220110_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folderpage',
            options={'verbose_name': 'Ordner Seite'},
        ),
    ]
